export const RECEIVE_ERROR = 'RECEIVE_ERROR'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_CURRENT = 'LOGIN_CURRENT'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'

export const RECEIVE_USER_LIST = 'RECEIVE_USER_LIST'
export const USER_DELETE_SUCCESS = 'USER_DELETE_SUCCESS'
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS'

export const RECEIVE_USER_ADDRESS_LIST = 'RECEIVE_USER_ADDRESS_LIST'
export const USER_ADDRESS_CREATED_SUCCESS = 'USER_ADDRESS_CREATED_SUCCESS'
export const USER_ADDRESS_UPDATE_SUCCESS = 'USER_ADDRESS_UPDATE_SUCCESS'
export const USER_ADDRESS_DELETE_SUCCESS = 'USER_ADDRESS_DELETE_SUCCESS'
export const USER_ADDRESS_SET_DEFAULT_SUCCESS = 'USER_ADDRESS_SET_DEFAULT_SUCCESS'
