export const RECEIVE_ERROR = 'RECEIVE_ERROR'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_CURRENT = 'LOGIN_CURRENT'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'

export const RECEIVE_USER_LIST = 'RECEIVE_USER_LIST'
